markdown: rdiscount
auto: true
title: blog.timmschoof.com
url: http://blog.timmschoof.com
email: hello@timmschoof.com
author: Timm Schoof
permalink: /:year/:month/:day/:title
description: "This is Timm Schoof's personal blog. It's covering tech, films, and general thoughts."
paginate: 4